CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(320) NOT NULL,
    email             VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT   pk_user              PRIMARY KEY (id),
    CONSTRAINT   name_is_blank        CHECK (name NOT LIKE ' ' AND name NOT LIKE ''),
    CONSTRAINT   email_is_not_correct CHECK (email LIKE '%@%')
);

CREATE TABLE IF NOT EXISTS items
(
    id                BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id           BIGINT NOT NULL,
    name              VARCHAR(320) NOT NULL,
    description       VARCHAR(320) NOT NULL,
    available         BOOLEAN NOT NULL,
    request           VARCHAR(320),
    CONSTRAINT   pk_items           PRIMARY KEY (id),
    CONSTRAINT   name_is_blank1     CHECK (name NOT LIKE ' ' AND name NOT LIKE ''),
    CONSTRAINT   fk_items_to_users  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id                BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    start_time        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id           BIGINT NOT NULL,
    booker_id         BIGINT NOT NULL,
    status            VARCHAR(320) NOT NULL,
    CONSTRAINT   pk_bookings               PRIMARY KEY (id),
    CONSTRAINT   fk_bookings_to_items      FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    id                BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    texts             VARCHAR NOT NULL,
    item_id           BIGINT NOT NULL,
    author_id         BIGINT NOT NULL,
    created           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT   pk_comments            PRIMARY KEY (id),
    CONSTRAINT   fk_comments_to_items   FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);

