CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(320) NOT NULL,
    email             VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT   pk_user              PRIMARY KEY (id),
    CONSTRAINT   name_is_blank        CHECK (name NOT LIKE ' ' AND name NOT LIKE ''),
    CONSTRAINT   email_is_not_correct CHECK (email LIKE '%@%')
);

CREATE TABLE IF NOT EXISTS items
(
    id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    name              VARCHAR(320) NOT NULL,
    description       VARCHAR(320) NOT NULL,
    available         BOOLEAN NOT NULL,
    request           VARCHAR(320),
    CONSTRAINT   name_is_blank      CHECK (name NOT LIKE ' ' AND name NOT LIKE ''),
    CONSTRAINT   fk_items_to_users  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    start_time        TIMESTAMP NOT NULL,
    end_time          TIMESTAMP NOT NULL,
    item_id           BIGINT NOT NULL,
    booker_id         BIGINT NOT NULL,
    status            VARCHAR(320) NOT NULL,
    CONSTRAINT   fk_bookings_to_items           FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT   fk_bookings_to_users           FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

