CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(320) NOT NULL,
    email             VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT   pk_user             PRIMARY KEY (id),
    CONSTRAINT   name_is_blank       CHECK (name NOT LIKE ' ' AND name NOT LIKE ''),
    CONSTRAINT   email_is_notcorrect CHECK (email LIKE '%@%')
);

CREATE TABLE IF NOT EXISTS items
(
    id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    name              VARCHAR(320) NOT NULL,
    description       VARCHAR(320) NOT NULL,
    available         BOOLEAN NOT NULL,
    request           VARCHAR(320),
    CONSTRAINT   name_is_blank      CHECK (name NOT LIKE ' ' AND name NOT LIKE ''),
    CONSTRAINT   fk_items_to_users  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

